repos:

# - repo: https://github.com/kynan/nbstripout
#   rev: 0.6.0
#   hooks:
#     - id: nbstripout

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: check-added-large-files
  - id: flake8
    args: [--max-line-length=100, --per-file-ignores=__init__.py:F401, '--ignore=E203,E402,E501,W503,F821,C901,E265,E266']

- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
  - id: black
    language_version: python3
    args: [--line-length=100]
    additional_dependencies: ['click==7.1.2']

- repo: https://gitlab.com/ljn/projects/rte/origami/rte-origami-precommit-hooks.git
  rev: 0.0.4
  hooks:
  - id: check-commit-message
    stages: [commit-msg]

- repo: local
  hooks:
  - id: tests
    name: run tests
    entry: pytest -v origami_indexers
    language: system
    types: [python]
    stages: [push]
