host = "0.0.0.0"
port = 6464
model_name = "OrdalieTech/Solon-embeddings-large-0.1"
#model_name=dangvantuan/sentence-camembert-large
#model_name=antoinelouis/biencoder-camembert-base-mmarcoFR
number_workers = 2
cuda_visible_devices = "0"