# Generated by Django 5.1.6 on 2025-04-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gpt", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="timestamp",
            new_name="created_at",
        ),
    ]
