# Generated by Django 5.1.6 on 2025-04-01 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gpt", "0002_rename_timestamp_message_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["-created_at"]},
        ),
    ]
