# Generated by Django 5.1.6 on 2025-04-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpt", "0003_alter_conversation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="rating",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
