# Generated by Django 5.1.6 on 2025-04-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpt", "0004_message_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="model",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
