from wattelse.summary.abstractive_summarizer import AbstractiveSummarizer
from wattelse.summary.extractive_summarizer import ExtractiveSummarizer, EnhancedExtractiveSummarizer
from wattelse.summary.localllm_summarizer import LocalLLMSummarizer
from wattelse.summary.chatgpt_summarizer import GPTSummarizer