ENDPOINT_CHECK_SERVICE = "/"
ENDPOINT_CREATE_SESSION = "/create-session"
ENDPOINT_SELECT_DOCS = "/select-docs"
ENDPOINT_QUERY_RAG = "/query-rag"
ENDPOINT_UPLOAD_DOCS = "/upload-docs"
ENDPOINT_REMOVE_DOCS = "/remove-docs"
ENDPOINT_CURRENT_SESSIONS = "/current-sessions"