# Generated by Django 5.1.1 on 2024-10-18 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0003_chat_answer_delay"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GPTChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_id", models.TextField()),
                ("conversation_id", models.UUIDField()),
                ("message", models.TextField()),
                ("response", models.TextField()),
                ("question_timestamp", models.DateTimeField()),
                ("answer_timestamp", models.DateTimeField(auto_now_add=True)),
                ("short_feedback", models.TextField(default="")),
                ("long_feedback", models.TextField(default="")),
                ("answer_delay", models.DurationField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
