#  Copyright (c) 2024, RTE (https://www.rte-france.com)
#  See AUTHORS.txt
#  SPDX-License-Identifier: MPL-2.0
#  This file is part of Wattelse, a NLP application suite.

# Generated by Django 5.1.1 on 2024-12-18 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("chatbot", "0007_create_user_profiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupProfile",
            fields=[
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="auth.group",
                    ),
                ),
                (
                    "rag_config",
                    models.CharField(default="azure_20241216", max_length=100),
                ),
                ("system_prompt", models.TextField(blank=True, default="", null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="GroupSystemPrompt",
        ),
        migrations.AddField(
            model_name="chat",
            name="rag_config",
            field=models.CharField(default="local_20240628", max_length=100),
            preserve_default=False,
        ),
    ]
