# Generated by Django 5.1.6 on 2025-03-31 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0008_groupprofile_delete_groupsystemprompt_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GPTChat",
        ),
    ]
