#  Copyright (c) 2024, RTE (https://www.rte-france.com)
#  See AUTHORS.txt
#  SPDX-License-Identifier: MPL-2.0
#  This file is part of Wattelse, a NLP application suite.

# Generated by Django 5.1.1 on 2024-10-18 17:56
# Generated by Django 5.1.6 on 2025-04-03 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_id", models.TextField()),
                ("conversation_id", models.UUIDField()),
                ("message", models.TextField()),
                ("response", models.TextField()),
                ("question_timestamp", models.DateTimeField()),
                ("answer_timestamp", models.DateTimeField(auto_now_add=True)),
                ("short_feedback", models.TextField(default="")),
                ("long_feedback", models.TextField(default="")),
                ("answer_delay", models.DurationField(blank=True, null=True)),
                ("relevant_extracts", models.JSONField(default=list)),
                ("group_system_prompt", models.TextField(default="")),
                ("rag_config", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
