# Generated by Django 5.1.6 on 2025-04-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0002_ragconversation_ragmessage_delete_chat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ragmessage",
            name="relevant_extracts",
            field=models.JSONField(default=list),
        ),
    ]
