#  Copyright (c) 2024, RTE (https://www.rte-france.com)
#  See AUTHORS.txt
#  SPDX-License-Identifier: MPL-2.0
#  This file is part of Wattelse, a NLP application suite.

# Generated by Django 5.0.2 on 2024-03-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_superuserpermissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superuserpermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': (('can_upload_documents', 'Can upload documents'), ('can_remove_documents', 'Can remove documents'), ('can_manage_users', 'Can manage users'))},
        ),
    ]
