#  Copyright (c) 2024, RTE (https://www.rte-france.com)
#  See AUTHORS.txt
#  SPDX-License-Identifier: MPL-2.0
#  This file is part of Wattelse, a NLP application suite.

# Generated by Django 5.0.3 on 2024-04-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_rename_timestamp_chat_answer_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="answer_delay",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
