# Generated by Django 5.0.7 on 2024-09-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_chat_answer_delay"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupSystemPrompt",
            fields=[
                ("group_id", models.TextField(primary_key=True, serialize=False)),
                ("system_prompt", models.TextField()),
            ],
        ),
    ]
