# Generated by Django 5.1.1 on 2024-11-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0004_gptchat"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="relevant_extracts",
            field=models.JSONField(default=list),
        ),
    ]
