# Generated by Django 5.1.1 on 2024-11-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_groupsystemprompt"),
        ("chatbot", "0005_chat_relevant_extracts"),
    ]

    operations = []
