# Generated by Django 5.1.1 on 2024-11-12 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0006_merge_20241112_1521"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="superuserpermissions",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("can_upload_documents", "Can upload documents"),
                    ("can_remove_documents", "Can remove documents"),
                    ("can_manage_users", "Can manage users"),
                    ("can_edit_group_system_prompt", "Can edit group system prompt"),
                ),
            },
        ),
    ]
