# Generated by Django 5.1.1 on 2024-11-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0007_alter_superuserpermissions_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="group_system_prompt",
            field=models.TextField(default=""),
        ),
    ]
