# Generated by Django 5.1.1 on 2024-12-13 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("chatbot", "0007_create_user_profiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupProfile",
            fields=[
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="auth.group",
                    ),
                ),
                ("llm_deployment", models.CharField(default="azure", max_length=10)),
                ("system_prompt", models.TextField(blank=True, default="", null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="GroupSystemPrompt",
        ),
    ]
