name: black-action
on: [push, pull_request]
jobs:
  linter_name:
    name: runner / black
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Black formatter
        uses: psf/black@stable
        with:
          options: "."
      - name: Commit black changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m ":art: Format Python code with psf/black" || echo "No changes to commit"
          git push || echo "No changes to push"
        # echo commands to prevent the action from failing if there are no changes to commit/push